---
AWSTemplateFormatVersion: 2010-09-09
Description: Example of EC2 Spot Fleet with Instance Weighting. Fractional Instances Weights
  are being used such that 1 unit of target capacity = 1000 vCPUs.
Metadata:
  Author:
    Description: Chad Schmutzer <schmutze@amazon.com>
  License:
    Description: 'Copyright 2017 Amazon.com, Inc. and its affiliates. All Rights Reserved.

      Licensed under the Amazon Software License (the "License"). You may not use this file
      except in compliance with the License. A copy of the License is located at

      http://aws.amazon.com/asl/

      or in the "license" file accompanying this file. This file is distributed on an "AS IS"
      BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
      License for the specific language governing permissions and limitations under the License.'
Outputs:
  spotFleetId:
    Description: The Spot Fleet request ID
    Value:
      Ref: spotFleet
Parameters:
  spotFleetTargetCapacity:
    Default: 1
    Description: EC2 Spot Fleet target capacity
    Type: Number
Resources:
  instanceProfile:
    DependsOn:
    - instanceRole
    Properties:
      Path: /
      Roles:
      - Ref: instanceRole
    Type: AWS::IAM::InstanceProfile
  instanceRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
        Version: 2012-10-17
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceforEC2Role
      Path: /
      Policies:
      - PolicyDocument:
          Statement:
          - Action:
            - ecs:UpdateContainerInstancesState
            Effect: Allow
            Resource: '*'
          Version: 2012-10-17
        PolicyName:
          Fn::Join:
          - '-'
          - - Ref: AWS::StackName
            - ecsUpdateContainerInstancesStatePolicy
      - PolicyDocument:
          Statement:
          - Action:
            - batch:Describe*
            Effect: Allow
            Resource: '*'
          Version: 2012-10-17
        PolicyName:
          Fn::Join:
          - '-'
          - - Ref: AWS::StackName
            - batchDescribeContainerInstancesStatePolicy
      - PolicyDocument:
          Statement:
          - Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            - logs:DescribeLogStreams
            Effect: Allow
            Resource: arn:aws:logs:*:*:*
          Version: 2012-10-17
        PolicyName:
          Fn::Join:
          - '-'
          - - Ref: AWS::StackName
            - cloudWatchLogsPolicy
    Type: AWS::IAM::Role
  spotFleet:
    DependsOn:
    - spotFleetRole
    Properties:
      SpotFleetRequestConfigData:
        AllocationStrategy: diversified
        IamFleetRole:
          Fn::GetAtt:
          - spotFleetRole
          - Arn
        LaunchSpecifications:
        - IamInstanceProfile:
            Arn:
              Fn::GetAtt:
              - instanceProfile
              - Arn
          ImageId: ami-045f1b3f87ed83659
          InstanceType: m4.16xlarge
          Monitoring:
            Enabled: true
          SubnetId: subnet-05ef7d72, subnet-fa2653a3, subnet-dc1c12b9, subnet-f1342dda, subnet-5b76f066
          UserData:
            Fn::Base64:
              Fn::Sub: '#!/bin/bash -xe

                echo "ECS_CLUSTER=uber_Batch_b7dbf56e-48b7-316a-80c9-81973bf0495c" >> /etc/ecs/ecs.config

                '
          WeightedCapacity: 0.064
        - IamInstanceProfile:
            Arn:
              Fn::GetAtt:
              - instanceProfile
              - Arn
          ImageId: ami-045f1b3f87ed83659
          InstanceType: c5.9xlarge
          Monitoring:
            Enabled: true
          SubnetId: subnet-05ef7d72, subnet-fa2653a3, subnet-dc1c12b9, subnet-f1342dda, subnet-5b76f066
          UserData:
            Fn::Base64:
              Fn::Sub: '#!/bin/bash -xe

                echo "ECS_CLUSTER=uber_Batch_b7dbf56e-48b7-316a-80c9-81973bf0495c" >> /etc/ecs/ecs.config

                '
          WeightedCapacity: 0.036
        ReplaceUnhealthyInstances: true
        TargetCapacity:
          Ref: spotFleetTargetCapacity
        TerminateInstancesWithExpiration: true
    Type: AWS::EC2::SpotFleet
  spotFleetRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - spotfleet.amazonaws.com
        Version: 2012-10-17
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AmazonEC2SpotFleetTaggingRole
      Path: /
    Type: AWS::IAM::Role
...
