---
AWSTemplateFormatVersion: 2010-09-09
Description: Example of EC2 Spot Fleet with Instance Weighting. Fractional Instances Weights
  are being used such that 1 unit of target capacity = 100 vCPUs.
Metadata:
  Author:
    Description: Chad Schmutzer <schmutze@amazon.com>
  License:
    Description: 'Copyright 2017 Amazon.com, Inc. and its affiliates. All Rights Reserved.

      Licensed under the Amazon Software License (the "License"). You may not use this file
      except in compliance with the License. A copy of the License is located at

      http://aws.amazon.com/asl/

      or in the "license" file accompanying this file. This file is distributed on an "AS IS"
      BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
      License for the specific language governing permissions and limitations under the License.'
Outputs:
  spotFleetId:
    Description: The Spot Fleet request ID
    Value:
      Ref: spotFleet
Parameters:
  spotFleetTargetCapacity:
    Default: 1
    Description: EC2 Spot Fleet target capacity
    Type: Number
Resources:
  spotFleet:
    DependsOn:
    - spotFleetRole
    Properties:
      SpotFleetRequestConfigData:
        AllocationStrategy: diversified
        IamFleetRole:
          Fn::GetAtt:
          - spotFleetRole
          - Arn
        LaunchSpecifications:
        - ImageId: ami-aff65ad2
          InstanceType: m3.2xlarge
          Monitoring:
            Enabled: true
          SubnetId: subnet-05ef7d72, subnet-fa2653a3, subnet-dc1c12b9, subnet-f1342dda, subnet-5b76f066
          WeightedCapacity: 0.08
        - ImageId: ami-aff65ad2
          InstanceType: r3.4xlarge
          Monitoring:
            Enabled: true
          SubnetId: subnet-05ef7d72, subnet-fa2653a3, subnet-dc1c12b9, subnet-f1342dda, subnet-5b76f066
          WeightedCapacity: 0.16
        - ImageId: ami-aff65ad2
          InstanceType: c3.4xlarge
          Monitoring:
            Enabled: true
          SubnetId: subnet-05ef7d72, subnet-fa2653a3, subnet-dc1c12b9, subnet-f1342dda, subnet-5b76f066
          WeightedCapacity: 0.16
        - ImageId: ami-aff65ad2
          InstanceType: i3.2xlarge
          Monitoring:
            Enabled: true
          SubnetId: subnet-05ef7d72, subnet-fa2653a3, subnet-dc1c12b9, subnet-f1342dda, subnet-5b76f066
          WeightedCapacity: 0.08
        ReplaceUnhealthyInstances: true
        TargetCapacity:
          Ref: spotFleetTargetCapacity
        TerminateInstancesWithExpiration: true
    Type: AWS::EC2::SpotFleet
  spotFleetRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - spotfleet.amazonaws.com
        Version: 2012-10-17
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AmazonEC2SpotFleetTaggingRole
      Path: /
    Type: AWS::IAM::Role
...
