apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-persist
  namespace: jhub
spec:
  capacity:
    storage: 123Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: fs-0f2818a5.efs.us-west-2.amazonaws.com
    path: "/"
 